leiyakenney/monster_shop_1906

app/views/layouts/_navbar.html.erb
app/views/layouts/application.html.erb

Navbar styling

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/layouts/_navbar.html.erb
app/views/users/new.html.erb
app/views/users/profile.html.erb
config/routes.rb
db/migrate/20190904215728_create_users.rb
db/schema.rb
spec/features/users/new_spec.rb
spec/models/user_spec.rb

Add User Registration functionality

Complete User Story 2

---

spec/features/users/login_spec.rb

Co-authored-by: Nancy Lee <24424825+nancylee713@users.noreply.github.com>
Co-authored-by: Mack Halliday <16658577+MackHalliday@users.noreply.github.com>
Co-authored-by: Leiya Kenney <45922590+leiyakenney@users.noreply.github.com>

Write tests for user login

---

app/controllers/admin/base_controller.rb
app/controllers/admin/dashboard_controller.rb
app/controllers/application_controller.rb
app/controllers/merchant/base_controller.rb
app/controllers/merchant/dashboard_controller.rb
app/controllers/sessions_controller.rb
app/views/admin/dashboard/index.html.erb
app/views/merchant/dashboard/index.html.erb
app/views/users/login.html.erb
config/routes.rb
db/seeds.rb
spec/features/users/login_spec.rb

-Add login functionality for 3 user types
-Create routes and views for each
-Add basic authorization functionality to each

User story 13

---

app/controllers/users_controller.rb
app/models/user.rb
spec/features/users/new_spec.rb

- Creates a basic flash message saying which fields are missing
- This will need styling updates when we're done, but it's at least functional

User Story 3

---

app/controllers/sessions_controller.rb
spec/features/users/login_spec.rb

-Redirect logged in users away from the login page

User stories 14 and 15

---

spec/features/users/new_spec.rb

RSPEC OK 
SimpleCov 100%
Co-authored-by: Nancy Lee <24424825+nancylee713@users.noreply.github.com>
Co-authored-by: Tyler Schaffer <48742436+tschaffer1618@users.noreply.github.com>
Co-authored-by: Leiya Kenney <45922590+leiyakenney@users.noreply.github.com>

Refactoring - Update user login spec for flash messages

---

app/controllers/sessions_controller.rb
config/routes.rb
spec/features/users/logout_spec.rb
spec/features/users/new_spec.rb

- Creates logout functionality
- Logout clears cart

User Story 16

---

spec/features/users/new_spec.rb

- Comments out non-working tests from email validation story - sorry!

User story 4 Tests Comment Out

---

app/controllers/sessions_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/users/new.html.erb
spec/features/users/new_spec.rb
spec/models/user_spec.rb

- Add password confirmation functionality in user model

Modify password confirmation field in form

---

app/controllers/application_controller.rb
app/views/layouts/_navbar.html.erb
spec/features/navigation_spec.rb

- Writes test for merchant dashboard showing up on merchant nav bar
- Adds merchant employee to application controller
- Includes Merchant Dashboard in merchant nav bar
- RSpec ok

User story 7

---

app/controllers/application_controller.rb
app/controllers/merchant/base_controller.rb
app/controllers/merchant/dashboard_controller.rb
app/controllers/sessions_controller.rb
app/views/layouts/_navbar.html.erb
spec/features/navigation_spec.rb
spec/features/users/login_spec.rb

- Adds merchant employee capabilities
- Writes tests for merchant navigation restrictions

User story 11

---

app/controllers/admin/users_controller.rb
app/controllers/application_controller.rb
app/controllers/cart_controller.rb
app/views/admin/users/index.html.erb
app/views/admin/users/show.html.erb
app/views/layouts/_navbar.html.erb
config/routes.rb
spec/features/navigation_spec.rb
spec/features/users/admin_users/authorization_spec.rb
spec/features/users/admin_users/users_index_spec.rb
spec/features/users/admin_users/users_show_spec.rb
spec/features/users/login_spec.rb
spec/features/users/merchant_users/authorization_spec.rb
spec/features/users/regular_users/authorization_spec.rb
spec/features/users/regular_users/show_spec.rb

-Customize nav bar for logged in admin user
-Admin user cannot visit '/cart' or '/merchant'
-Add authorization_spec files for admin, merchant, and regular users
-Add admin_user users index page with links to each users' admin show page
-Add admin_user user show page

Complete US #8, 12, 45, 46

---

app/controllers/merchant/dashboard_controller.rb
app/views/layouts/_navbar.html.erb
config/routes.rb
spec/models/user_spec.rb

Co-authored-by: Nancy Lee <24424825+nancylee713@users.noreply.github.com>
Co-authored-by: Mack Halliday <16658577+MackHalliday@users.noreply.github.com>
Co-authored-by: Leiya Kenney <45922590+leiyakenney@users.noreply.github.com>

Clean up tests after merging multiple branches

---

app/controllers/users_controller.rb
app/views/users/edit.html.erb
app/views/users/edit_password.html.erb
app/views/users/new.html.erb
config/routes.rb
spec/features/users/new_spec.rb
spec/features/users/regular_user/edit_spec.rb
spec/models/merchant_spec.rb

- Updates all forms to be form_for
- Updates fill_in titles to be strings instead of symbols to work with the form_fors
- Updates user_controller to include @user definition
- Updates /register and /profile routes
- Updates cities test to always keep order the same
- Rspec runs ok
- SimpleCov is at 99.84% - will update later

User Story 4

---

Gemfile
Gemfile.lock
app/controllers/orders_controller.rb
app/controllers/users_controller.rb
app/models/item.rb
app/models/item_order.rb
app/models/order.rb
app/models/user.rb
app/views/users/show_orders.html.erb
config/routes.rb
db/migrate/20190907162016_add_user_to_item_orders.rb
db/migrate/20190907165927_add_status_to_item_orders.rb
db/schema.rb
spec/factories.rb
spec/features/items/destroy_spec.rb
spec/features/merchants/statistics_spec.rb
spec/features/users/regular_user/profile_order_spec.rb
spec/models/item_orders_spec.rb
spec/models/item_spec.rb
spec/models/merchant_spec.rb
spec/models/order_spec.rb
spec/models/user_spec.rb
spec/rails_helper.rb

- Install 3 gems
- Use factory bot to create stubbed objects
- Modify user_spec model test
- Add user id column to item order table
- had to follow error messages to modify related files
- Create a spec test for showing profile order page
- Create a profile order show page displaying a table of order info

User story 23

---

app/views/users/show_orders.html.erb
spec/features/users/regular_user/profile_order_spec.rb

- Add additional attributes (i.e., `Order ID`, timestamps, and grand total for each order)
- `Order ID` is clickable, linked to each order show page

User story 25 - User Profile displays Orders

---

app/models/item_order.rb
app/models/merchant.rb
app/models/order.rb
app/views/users/show_orders.html.erb
db/migrate/20190907165927_add_status_to_item_orders.rb
db/migrate/20190909145129_add_status_to_orders.rb
db/schema.rb
spec/features/orders/new_spec.rb
spec/features/users/merchant_users/merchant_dash_spec.rb
spec/features/users/regular_user/profile_order_spec.rb
spec/models/item_orders_spec.rb
spec/models/order_spec.rb

- Updates item_order status to be fulfilled/unfulfilled 
- Updates order status to be pending/packaged/shipped/cancelled
- Updates syntax from renaming

Change Statuses

---

app/controllers/merchants_controller.rb
app/models/merchant.rb
spec/features/users/admin_users/merchants_index_spec.rb
spec/models/merchant_spec.rb

-Modify enable/disable merchant functionality to activate/deactivate that merchant's items
-New methods activate_items and deactivate_items in the merchant class
-Model tests for those two methods completed as well

User stories 49 & 51

---

app/models/user.rb

- Fixes password bug when you update a profile

Clean Up 2

---

app/controllers/merchant/items_controller.rb
app/controllers/reviews_controller.rb
app/views/reviews/_form_review.html.erb
app/views/reviews/edit.html.erb
app/views/reviews/new.html.erb
spec/features/reviews/edit_spec.rb
spec/features/reviews/new_spec.rb

- Use partial for creating and editing a review form
- Switch to `form_for` from `form_tag` in these forms and modify related spec tests
- Rectify errors pertaining to #destroy within merchant_items controller

Form routes

---

app/controllers/admin/dashboard_controller.rb
app/controllers/orders_controller.rb
app/models/item_order.rb
app/models/order.rb
app/views/admin/dashboard/index.html.erb
config/routes.rb
db/migrate/20190909145129_add_status_to_orders.rb
db/migrate/20190909231240_add_user_to_orders.rb
db/schema.rb
db/seeds.rb
spec/features/users/admin_users/dashboard_orders_spec.rb
spec/models/order_spec.rb

- Admin can see all orders, orders link to user profile
- Orders sorted by pending, packaged, shipped, and cancelled
- Update seed file with correction to order_4
- Updates to database:
- status in Order table now an integer
- enum used for orders status [packaged, pending, shipped, cancelled]
- default value for pending = 1
- Updates to relationship in ItemOrder:
- Connected users and orders through ItemOrder
- Can now call order.users.first to get users for an order
- Please see admin order controller. May need to move @orders sort to model
- "Ship Item" button created in admin order index view. Admin can click Ship Item button and order status updated to shipped
Rspec OK
SimpleCov OK
Models OK

User story 42 and 43 - Admin Ship Item

---

app/controllers/application_controller.rb
app/views/orders/show.html.erb
db/seeds.rb
spec/features/orders/show_spec.rb

- Update Regular User's order show page: removed extra columns, update logic, add link_to_if
- Update seed file with reviews and added merchant users to Dunder merchant shop 
Rspec OK 
SimpleCov 99.72% (Need to remove controller params using old form_tag?)

Refactor - Seed File, Regular User's Order

---

app/controllers/merchant/items_controller.rb
app/models/item.rb
app/views/merchant/items/index.html.erb
config/routes.rb
spec/features/users/merchant_users/add_item_spec.rb
spec/features/users/merchant_users/item_index_spec.rb

-Add functionality for merchant admin to activate/deactivate items

User story 35 36

---

spec/models/item_spec.rb
spec/models/merchant_spec.rb
spec/models/order_spec.rb

- Gets model tests up to 100% coverage for: 
- order.rb
- merchant.rb
- item.rb

Model Tests

---

app/models/item.rb
app/views/items/index.html.erb
spec/features/items/index_spec.rb

- Creates top/bottom 5 methods in item model
- Updates item view to include top/bottom tables
- Updates tests
- RSpec okay
- SimpleCov 99.73%

User story 52

---

spec/features/items/index_spec.rb
spec/models/item_spec.rb

User story 52 Model Test

---

app/controllers/admin/dashboard_controller.rb
app/controllers/orders_controller.rb
app/models/order.rb
app/views/admin/dashboard/index.html.erb
spec/features/users/admin_users/dashboard_orders_spec.rb
spec/models/order_spec.rb

- Rspec OK
- SimpleCov OK 
- Model covered

Refactor admin orders - Move methods from controllers to models

---

app/views/orders/show.html.erb
app/views/users/login.html.erb
app/views/welcome/index.html.erb

- Adds some gifs n breaks n  stuff

Appearance updates

---

app/controllers/orders_controller.rb
app/views/orders/new.html.erb

- Pre-populates address form with registered user's info

User story 23 Update

---

app/controllers/orders_controller.rb
spec/features/orders/creation_spec.rb

- Requires rails_helper
- Adds @ back onto @user in order_controller
- RSpec okay
- SimpleCov 100%

User story 23 Final

---

app/views/orders/new.html.erb

- Updates new order page tag so table aligns

Small tag update

---

app/controllers/users_controller.rb
app/views/items/show.html.erb
app/views/users/show_order.html.erb
app/views/users/show_orders.html.erb
config/routes.rb
spec/features/users/regular_user/profile_order_spec.rb

- `/profile/orders` page show brief order info
- `profile/orders/:id` page show order & detailed item info

Edit User stories 25 & 26

---

app/controllers/users_controller.rb
app/models/item_order.rb
app/views/users/show_order.html.erb
spec/models/item_orders_spec.rb

Modify #show_order and dry up code thru before_action filter

Modify Users controller actions

---

app/views/merchant/dashboard/_merchant_info.html.erb
spec/features/users/admin_users/merchant_show_spec.rb

- Makes it so admins can't see order show pages

Admin seeing orders

---

db/seeds.rb

Co-authored-by: Tyler Schaffer 
<48742436+tschaffer1618@users.noreply.github.com>
Co-authored-by: Nancy Lee 
<24424825+nancylee713@users.noreply.github.com>
Co-authored-by: Mack Halliday 
<16658577+MackHalliday@users.noreply.github.com>

Adds destroy_all to seeds

---

app/controllers/addresses_controller.rb
app/controllers/users_controller.rb
app/models/address.rb
app/models/order.rb
app/models/user.rb
app/views/addresses/edit.html.erb
app/views/addresses/new.html.erb
app/views/cart/show.html.erb
app/views/users/edit.html.erb
app/views/users/new.html.erb
app/views/users/profile.html.erb
config/routes.rb
db/migrate/20190915223922_create_addresses.rb
db/migrate/20190916224443_remove_address_from_users.rb
db/migrate/20190916224502_remove_city_from_users.rb
db/migrate/20190916224516_remove_state_from_users.rb
db/migrate/20190916224532_remove_zipcode_from_users.rb
db/migrate/20190918095805_remove_address_from_orders.rb
db/migrate/20190918095921_remove_city_from_orders.rb
db/migrate/20190918095937_remove_state_from_orders.rb
db/migrate/20190918095955_remove_zip_from_orders.rb
db/migrate/20190918130321_add_address_to_orders.rb
db/schema.rb
spec/factories.rb
spec/features/addresses/new_spec.rb
spec/features/users/new_spec.rb
spec/models/address.rb

I'm not going to lie, most things are broken. I restarted this yesterday after the retake so I did as much coding as I could, even though there are broken things. It's not my best work, but it's what I have at this point. Sorry.

CRUD Functionality

---

app/controllers/users_controller.rb
config/routes.rb
spec/factories.rb
spec/models/user_spec.rb

- Still had some tests not passing from last mod
- Routes rewritten with resources and scope

Prework reconfig
